# Generated by Django 3.2 on 2023-06-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductType',
            new_name='Chat',
        ),
    ]
